### ISSUE TITLE
Append timestamp onto the end of downloaded patch files

### ISSUE THREAD

**Issue by markshust** [enanobots/m2-datapatchcreator-simpledata#3]
The file I downloaded had the name `CmsPageHome.php`. The problem with this is that subsequent data patch updates to this same file will not execute, because entries in `patch_list` show this as a record already executed:

```
MarkShust\MyData\Setup\Patch\Data\CmsPageHome
```

I'd like some sort of YYYYMMDDhhmm timestamp appended to this file. For example, if the patch was named `CmsPageHome202110201337`, the entry in the `patch_list` db table would be:

```
MarkShust\MyData\Setup\Patch\Data\CmsPageHome202110201337
```

A subsequent change to this file will be downloaded with a new timestamp, causing it to re-run and an additional entry be added to `patch_list` (which is what would be desired).

**Comment by enanobots** [comment]
This will be added / changed in the next release, in few days from now.

**Comment by enanobots** [comment]
This has been added in version 1.0.5, configurable option. 
@markshust enjoy ;-)
